package com.homeflex.features.property.dto.response;

import com.homeflex.core.dto.response.UserDto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.List;
import java.util.UUID;

public record PropertyDto(
        UUID id,
        String title,
        String description,
        String propertyType,
        String listingType,
        BigDecimal price,
        String currency,
        String address,
        String city,
        String stateProvince,
        String country,
        String postalCode,
        BigDecimal latitude,
        BigDecimal longitude,
        Integer bedrooms,
        Integer bathrooms,
        BigDecimal areaSqm,
        Integer floorNumber,
        Integer totalFloors,
        String cancellationPolicy,
        BigDecimal cleaningFee,
        BigDecimal securityDeposit,
        Boolean instantBookEnabled,
        Boolean isAvailable,
        LocalDate availableFrom,
        String status,
        Integer viewCount,
        Integer favoriteCount,
        // Policy fields
        LocalTime checkInTime,
        LocalTime checkOutTime,
        Integer starRating,
        Boolean petsAllowed,
        Boolean smokingAllowed,
        Boolean childrenAllowed,
        Integer minStayNights,
        Integer maxStayNights,
        String houseRules,
        String rejectionReason,
        LocalDateTime submittedAt,
        LocalDateTime approvedAt,
        List<PropertyImageDto> images,
        List<PropertyVideoDto> videos,
        List<AmenityDto> amenities,
        UserDto landlord,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
) {}
