input {
  tcp {
    port => 50000
    codec => json_lines
  }
}

filter {
  # Add any required filters here
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "homeflex-backend-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
